name: Build and Push Image to ECR
on:
  push:
    branches:
      - cd-pipy
  workflow_dispatch:

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: echo "building and publishing"
