name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    container:
      image: fedora:latest
      env:
        # Set a mock Git tag for dynamic versioning
        SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0.dev0"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Important for 3.6: allows downloading from the versions-archive
          allow-prereleases: true
          if: matrix.python-version == "3.6"

      - name: Install dependencies
        if: matrix.python-version == "3.6"
        run: |
          python -m pip install --upgrade pip
          pip install . pytest setuptools setuptools-scm  # Or uv pip install if using uv

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v7
        with:
          if: matrix.python-version != "3.6"
          python-version: ${{ matrix.python-version }}
          version: "0.9.26" # uv version
          enable-cache: true

      - name: Install dependencies
        if: matrix.python-version != "3.6"
        run: uv sync --group test --group coverage --no-dev

      - name: Run tests
        if: matrix.python-version != "3.6"
        run: uv run pytest --cov=productmd tests

  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run bandit
        run: uvx bandit -c pyproject.toml -r productmd/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run linter
        run: uvx ruff check

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run formatter check
        run: uvx ruff format --check
