name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"

    container:
      image: fedora:latest
      env:
        # Set a mock Git tag for dynamic versioning
        SETUPTOOLS_SCM_PRETEND_VERSION: "0.0.0.dev0"

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and setup Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
          version: "0.9.26" # uv version
          enable-cache: true

      - name: Install dependencies
        run: uv sync --group test --group coverage --no-dev

      - name: Run tests
        run: uv run pytest --cov=productmd tests

  bandit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run bandit
        run: uvx bandit -c pyproject.toml -r productmd/

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run linter
        run: uvx ruff check

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv and Python interpreter
        uses: astral-sh/setup-uv@v7
        with:
          python-version-file: ".python-version"
          version: "0.9.26"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group dev

      - name: Run formatter check
        run: uvx ruff format --check
