# File: .github/workflows/deploy.yml
name: Deploy to Server
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Image to ECR"] #Its the name of an workflow
    types:
      - completed
jobs:
  deploy:
    name: Deploy to Server
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy Application
        run: |
          echo "Deploying application to server..."
          # Add your deployment script here
